import type { Metadata } from "next";
import { Rubik, Gasoek_One} from "next/font/google";
import "./globals.css";

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
});

const gasoek = Gasoek_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-gasoek",
});

export const metadata: Metadata = {
  title: "Party Poopers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} ${gasoek.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
